---
- name: be sure required services are installed
  yum: name={{item}} state=installed
  with_items:
    - wget
    - java-1.8.0-openjdk.x86_64

- name: conf jenkins rpm repo
  shell: "{{item}}"
  with_items:
    - "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"
    - "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: be sure jenkins is installed
  yum: name=jenkins state=installed

- name: be sure jenkins is enabled
  service: name='jenkins' state=started enabled=yes

- name: allow firewall
  command: "{{item}}"
  with_items:
    - "firewall-cmd --zone=public --add-port=8080/tcp --permanent"
    - "firewall-cmd --zone=public --add-service=http --permanent"
    - "firewall-cmd --reload"



...