server:
  port: 80

spring:
  data:
    mongodb:
      uri: "mongodb://10.220.132.186:8080/crawler_service"
    rest:
      basePath: "/api/0.1/"
      defaultMediaType: "application/json"



  jackson:
    serialization:
      write_dates_as_timestamps: false