export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

// Dashboard Mutation Event Types
export const RECEIVE_DURATION_DATA = 'RECEIVE_DURATION_DATA'

export const RECEIVE_DEPLOY_DATA = 'RECEIVE_DEPLOY_DATA'

export const RECEIVE_TEST_DATA = 'RECEIVE_TEST_DATA'

export const SHUFFLE = 'SHUFFLE'

export const SORT_TEST_SCENARIOS = 'SORT_TEST_SCENARIOS'

export const CLEAN_TEST_SCENARIOS = 'CLEAN_TEST_SCENARIOS'

export const RECEVIE_LATEST_TEST_SCENARIOS = 'RECEVIE_LATEST_TEST_SCENARIOS'

export const RECEVIE_RECENT_PIPELINE_TRENDS = 'RECEVIE_RECENT_PIPELINE_TRENDS'

export const RECEVIE_LATEST_DEPLOY_STATUS = 'RECEVIE_LATEST_DEPLOY_STATUS'

export const GET_LATEST_DEPLOY_STATUS_BY_PAGE = 'GET_LATEST_DEPLOY_STATUS_BY_PAGE'

export const RECEVIE_FAILED_DEPLOYMENT = 'RECEVIE_FAILED_DEPLOYMENT'

export const RECEVIE_VERIFY_LIST = 'RECEVIE_GET_VERIFY_LIST'

export const RECEVIE_TESTBEDS_INFO = 'RECEVIE_TESTBEDS_INFO'

export const RECEIVE_USER_INFORMATION = 'RECEIVE_USER_INFORMATION'

export const RECEIVE_CANCEL_RESPOSE = 'RECEIVE_CANCEL_RESPOSE'
