// owners are found at https://confluence.community.veritas.com/pages/viewpage.action?spaceKey=APPSOL&title=Feature+Maintenance

export const OWNER = {
  // nba pipeline
  'nba_upgrade_rpm_main_smoke': 'WAN (Saipu)',
  'nba_main_regression_xclish_va': 'Tigerwing (Saipu)',
  'nba_main_regression_upgrade_smoke_va': 'Rivendell (Crono)',
  'nba_main_regression_systemtest_e2e_va': 'Diamond (Jenny)',
  'nba_main_regression_supportability_va': 'WAN (Saipu)',
  'nba_main_regression_software_manage_va': 'Tigerwing (Saipu)',
  'nba_main_regression_security_va': 'Libra (Amos)',
  'nba_main_regression_storage': 'Orion (Jatheen)',
  'nba_main_regression_network': 'MillenniumFalcon (Harry)',
  'nba_main_regression_netbackup': 'Acadia (Subbu)',
  'nba_main_regression_gui_sanity': 'Autobots (Arash)',
  'nba_main_regression_platform_gui': 'Sequoia (Subbu)',
  'nba_main_regression_fqdn': 'Touchstone (Tony)',
  'nba_main_regression_systemtest': 'Divergent (Angela)',
  'nba_main_regression_iscsi': 'Sequoia (Subbu)',
  'nba_main_regression_dbshares': 'Incredibles (Jatheen)',
  'nba_main_regression_autosupport': 'Matrix (John)',
  'nba_main_regression_network_va': 'WAN (Saipu)',
  'nba_main_regression_d2c': 'MillenniumFalcon (Harry)',
  'nba_main_regression_autosupport_va': 'WAN (Saipu)',
  'nba_main_regression_fcr': 'Interstellar (Harry)',
  'nba_main_regression_sanity_va': 'Brio (Wendy)',
  'nba_main_regression_resiliency': 'HALO (Jianping)',
  'nba_main_regression_vxhelp': 'Libra (Kenneth)',
  'nba_main_regression_storage_va': 'Tigerwing (Saipu)',
  'nba_main_regression_autosupport2_va': 'Aladdin (John)',
  'nba_main_regression_san': 'Interstellar (Harry)',
  'nba_main_regression_security_authorization_va': 'WAN (Saipu)',
  'nba_main_regression_sanity': 'Autobots (Arash)',
  'nba_main_regression_security': 'Libra (Amos)',
  'nba_main_regression_soa': 'Avengers (Rohit)',
  'nba_main_regression_sanity2_va': 'Brio (Wendy)',
  'nba_main_regression_wanopt': 'WAN (Saipu)',
  'nba_main_regression_secure_comms': 'Libra (Amos)',
  // long regression pipeline
  'nba_main_long_regression_upgrade_nightly': 'Revendell (Crono)',
  'nba_main_long_regression_workflow': 'Matrix (John)',
  'nba_main_long_regression_systemtest_upgrade': 'Discovery (Daisy)',
  'nba_main_long_regression_systemtest_autosupport': 'Aladdin, Matrix (John)',
  'nba_main_long_regression_upgrade_nightly_va': 'Revendell (Crono)',
  'nba_main_long_regression_systemrestore': 'Touchstone (Tony Su)',
  'nba_main_long_regression_storage': 'Incredibles (Jatheen)',
  'nba_main_long_regression_fc_clish': 'Interstellar (Harry)',
  'nba_main_long_regression_HA_system_testbedc2': 'HALO (JianPing Song)',
  'nba_main_long_regression_HA_system_test': 'Discovery (Daisy)',
  'nba_main_long_regression_fcr_gui': 'Interstellar (Harry)',
  'nba_main_long_regression_autosupport': 'Aladdin, Matrix (John)',
  'nba_main_long_regression_l10n_chinese': 'Icebreaker (Lei)',
  'nba_main_long_regression_l10n_japanese': 'Icebreaker (Lei)',
  'nba_main_long_regression_resiliency': 'HALO (JianPing)',
  'nba_main_long_regression_network': 'MillenniumFalcon (Harry)',
  'nba_main_long_regression_share_ir': 'Incredibles (Jatheen)',
  // velocity pipeline
  'velocity_main_regression_vva': 'Touchstone, (Tony Su)',
  'velocity_main_regression_upgrade_smoke': 'Touchstone, (Tony Su)',
  'velocity_main_regression_storage': 'Touchstone, (Tony Su)',
  'velocity_main_regression_autosupport': 'Touchstone, (Tony Su)',
  'velocity_main_regression_network': 'Touchstone, (Tony Su)',
  'velocity_main_regression_others': 'Touchstone, (Tony Su)',
  'velocity_main_regression_sanity': 'Touchstone, (Tony Su)'
}
